# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Github Actions requires a single row to be added to the build matrix.
        # See https://help.github.com/en/articles/workflow-syntax-for-github-actions.
        name: [
          ubuntu-18.04-gcc-aarch64-linux-gnu
        ]
        
        include:
          - name: ubuntu-18.04-gcc-8
            os: ubuntu-18.04
            compiler: gcc
            version: "8"
          - name: ubuntu-18.04-gcc-9
            os: ubuntu-18.04
            compiler: gcc
            version: "9"
          - name: ubuntu-18.04-gcc-9
            os: ubuntu-18.04
            compiler: gcc
            version: "aarch64-linux-gnu"



    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install (Linux)
      if: runner.os == 'Linux'
      run: |
        # Required for libc6-dbg:i386 and g++-multilib packages which are
        # needed for x86 builds.
        sudo dpkg --add-architecture i386
        # clang-3.7 and earlier are not available in Bionic anymore so we get
        # them from the Xenial repositories instead.
        sudo add-apt-repository "deb http://dk.archive.ubuntu.com/ubuntu/ xenial main"
        sudo add-apt-repository "deb http://dk.archive.ubuntu.com/ubuntu/ xenial universe"
        # LLVM 9 is not in Bionic's repositories so we add the official LLVM repository.
        if [ "${{ matrix.compiler }}" = "clang" ] && [ "${{ matrix.version }}" = "9" ]; then
        sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
        fi
        sudo apt-get update
        # libc6-dbg:i386 is required for running valgrind on x86.
        sudo apt-get install -y ninja-build valgrind libc6-dbg:i386
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
        sudo apt-get install -y g++-${{ matrix.version }}
        echo "::set-env name=CC::gcc-${{ matrix.version }}"
        echo "::set-env name=CXX::g++-${{ matrix.version }}"
        else
        sudo apt-get install -y clang-${{ matrix.version }} g++-multilib
        echo "::set-env name=CC::clang-${{ matrix.version }}"
        echo "::set-env name=CXX::clang++-${{ matrix.version }}"
        fi
    - name: Install deps
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install build-essential checkinstall libboost-system-dev libboost-python-dev libboost-chrono-dev libboost-random-dev libssl-dev
        ./autotool.sh
        ./configure --disable-debug --enable-encryption --with-boost-libdir=/usr/lib/aarch64-linux-gnu --with-libiconv CXXFLAGS="-std=c++14"
        make -j80
